### ISSUE TITLE
ImportError: cannot import name 'run_glide_docking' from 'pose_prediction'

### ISSUE THREAD

**Issue by djbpark1** [VirtualFlow/VFU#1]
https://github.com/VirtualFlow/VFU/blob/cee95941f65319471a9d866e68bca2184fb5524c/initiate_calc.py#L15

`run_glide_docking` does not exist in `VFU/pose_prediction.py`

**Comment by akshat998** [comment]
Bug fixed (the function was split into three a while back) :)
