### ISSUE TITLE
import LigprepJob, LigprepSettings with schrodinger

### ISSUE THREAD

**Issue by sdyln0** [VirtualFlow/VFU#4]
I use your VFVS and VFU, they are really helpful! But I meet some problem when using glide:

Regarding to the code, I need" from schrodinger.application.ligprep import LigprepJob, LigprepSettings", but I can't find LigprepJob and LigprepSettings module in two versions of schrodinger(2021,2023). I need to know which version is compatible with your code. Thank you very much for your help!

**Comment by akshat998** [comment]
Hi @sdyln0, 

Thank you for your message :)

Just to make sure that the sdchordinger license is valid & everything is working, are you able to run the following? 
```
from schrodinger.job import jobcontrol as jc
from schrodinger.application.glide import glide
```

Regards
Akshat

**Comment by akshat998** [comment]
Please feel free to re-open the issue if not resolved :)
